
version: "3.9"
services:
    automl:
      build:
        context: /home/brandon/autoML/app
        dockerfile: Dockerfile
        args:
          - USER=${USER}
          - BASE_IMAGE_ARG=${BASE_IMAGE}
      volumes:
        - type: bind
          source: /home/${USER}/autoML/app
          target: /home/${USER}
      ports:
        - "8888:8888"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
      image: automl:latest
